name: rithuuu
on: push
jobs: 
  first:
    runs-on: ubuntu-latest
    steps:
      - name: printing jobs
        run: echo "complete maths"

  build:
    runs-on: ubuntu-latest
    needs: first
    steps: 
      - run: echo "connected" 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "next connection"